initial commit
i80287/course-project pull request #1
Opened 2024-01-18 23:38 UTC by i80287

2024-02-08 13:34 UTC, DimaTrushin commented on ACTrie.hpp
> +using std::uint32_t;
Лучше не делать для типов таких юзингов. Лучше вводить псевдонимы типа
using Size = std::size_t;
Ты таким образом можешь дать содержательное название типу и будет понятно зачем он используется. Size -- не лучшее название, потому ты можешь лучше придумать. Это не поможет компилятору следить за типами (потому что это псевдонимы) но поможет программисту. На худой конец можно так и написать using size_t = std::size_t;

2024-02-08 13:34 UTC, DimaTrushin commented on ACTrie.hpp
> +    static_assert(std::max(kNullNodeIndex,
Может быть стоит сделать constexpr функцию с именем areParametersValid и тут ее дернуть в static_assert, чтобы было понятно, что ты просто проверил, что константы выше корректные.

Вообще, когда у тебя есть много разных констант настроечных, то их можно спрятать в отдельный класс Pallette (палитру, можно другое название). Причем этот настроечный класс может быть шаблонным параметром текущего класса. И все настройки и проверки корректности можно вынести туда.

2024-02-08 13:34 UTC, DimaTrushin commented on ACTrie.hpp
> +    void ComputeLinks();
Меня всегда настораживают методы, которые ничего не принимают и ничего не возвращают. Такие методы явно работают со скрытым состоянием. Это ничем не лучше, чем работа с глобальными переменными и глобальными функциями. Если метод класса должен что-то сделать с данными класса, то лучше создать статический метод, который принимает только нужные данные и имеет нормальное название. Не забывай, что переменные класса -- это глобальные данные для методов класса. Не надо с ними работать неявно.

2024-02-08 14:44 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Есть большие проблемы с дизайном.
1) Ты слепил вместе event loop (почтальена) и view.
2) Во view у тебя какая-то поебень с callback-ами. Не надо смешивать разные методы передачи данных. Если ты используешь observer pattern, то используй его везде.
3) Я так и не увидел как у тебя модель получает данные. Где контроллер или его аналог? Кто дергает модель за ручки?
4) У тебя некорректный и не безопасный обзервер паттерн.

2024-02-08 14:44 UTC, DimaTrushin commented on ACTrie.cpp
> +        }
- Почему не сделать так
```cpp
int32_t sigma = conver???(*iter);
```
где вместо ??? содержательное название и уже туда спрятот все эти проверки с case sensetive?

- И еще вопрос. А зачем понадобилось делать конвертации? У тебя в содержательном коде идет низкоуровневая работа. Это означает, что у тебя нет достаточного количества методов, которые позволяют получать доступ к данным и ты получаешь этот доступ не в том формате и потому вместо содержательной работы ты тут делаешь какие-то касты. Да еще и не static_cast, а прям старые добрые Си касты. Это плохо. Убрать.

2024-02-08 14:44 UTC, DimaTrushin commented on ACTrie.cpp
> +        // Jump up through compressed suffix links
Раз есть комментарий, то почему нельзя тут вызвать функцию с названием отраженным в комментарии?

2024-02-08 14:44 UTC, DimaTrushin commented on ACTrie.cpp
> +            find_callback(text.substr(l, word_length), l);
Какого хрена тут происходит?

2024-02-08 14:44 UTC, DimaTrushin commented on ACTrie.cpp
> +            if (child_index != kNullNodeIndex) {
У тебя 4 вложенных scope даже в ядре Linux запрещено иметь более 3. Ну тут явно колбаса требующая рефакторинга.

2024-02-08 14:44 UTC, DimaTrushin commented on ACTrie.cpp
> +        for (size_t sigma = 0; sigma != kAlphabetLength; ++sigma) {
Я всегда с опаской смотрю на вложенные циклы. В одном то цикле сложно следить за инвариантом. А когда они вложены, то это обычно мрак.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    glfwTerminate();
А эти не кидают исключения?

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +          },
Никогда не пиши содержательную работу в этих методах. Делай проброс методов к методам класса например так
```cpp
: port_([this](Data data){handleData(data);}, do_nothing, do_nothing) {}
```
где handleData -- это метод this с говорящим названием. И вся работа выполняется классом, а не этой лямбдой. Суть этой лямбды связать поступающие данные на порт с методом, который надо вызвать. А не в содержательной работе.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    fprintf(stderr, "Glfw Error %d: %s\n", error,
Почему ты используешь такие низкоуровневые методы вывода? Почему не std::cout?

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.hpp
> +    std::vector<ModelType::word_length_t>* actrie_words_lengths_ = nullptr;
Это очень плохо. Ты хранишь скрытые ссылки на данные в другом объекте. Это нарушение как минимум правил доступа. Да ты можешь передать ссылки на эти данные в какой-то метод, но зачем эти адреса хранить между вызовами? Если нужно такое хранение, То как минимум эти данные должен запоминать порт, а мы лишь из него можем запросить их. Кроме того, при неблокирующих вызовах у тебя тут могут быть большие проблемы. Потому что ты еще не отрисовал старые данные, а они уже изменились или переехали. Опасно сложных системах передавать указатели и ссылки на постоянное хранение. Убрать.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.hpp
> +    GLFWwindow* window_ = nullptr;
Проблема возникает из-за того, что не может быть сформирован деструктор по умолчанию. Это решается кастомным deleter-ом. Либо своей собственной оберткой.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.hpp
> +    bool suppressor_ = false;
Плохое  название. Это не супрессор, а флаг для супрессора. Я предпочитаю делать супрессор lockable, чтобы можно было его использовать с std::lock_guard.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +        OnError("Unable to init glfw");
Если бы ты не владел тут сразу несколькими ресурсами, то мог бы спокойно кидать исключения при построении. Теперь понятно откуда у тебя такие костыли.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    window_ = window;
Если ты не определяешь объект в списке инициализации, ты что-то делаешь не так в 99% случаев.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    // if (ImGui::Button("Clear")) {
Не оставляй закомментированный код. Зачем тебе git с его поддержкой версий, если ты оставляешь закомментированный код? Убрать. Гит помнит всю историю и хранит весь код. Если нужно поиграться, то создаешь локально тестовую ветку, там играешь, а потом через checkout пикаешь нужные файлы.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +void Drawer::Render() {
Порядок методов в cpp файле должен быть точно такой же как в h файле! Как я блять должен это все искать?

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    constexpr ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);
Волшебная константа.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    glfwPollEvents();
Это должен делать event loop, а не view.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    UpdateState();
1) Нарушение уровня абстракции. Ты до и после этой строки говоришь на языке машинного кода, а тут у тебя бизнес логика.
2) Какого хрена Render обновляет состояние!? Что за поебень тут происходит?

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    constexpr ImU32 kGrayColor = IM_COL32(50, 50, 50, 255);
Заведи структуру Pallette (палитру), в которой будут храниться цвета для всех назначений. И храни структуру этого типа в классе и обращайся к ней за нужными цветами.

2024-02-08 14:44 UTC, DimaTrushin commented on Drawer.cpp
> +    // TODO: replace magic numbers with constants
Вместо констант можно сделать структуру параметров для значений уже не палитру, а просто значения размеров тех или иных объектов. Тогда можно сделать это все  настраиваемым.

2024-02-08 14:44 UTC, DimaTrushin commented on Observable.hpp
> +    void Subscribe(ObserverType* observer, SubscribeDataType data);
А как у тебя notify будет происходить? Ты тут сплел вместе subscribe и notify. То есть ты подписываешь и оповещаешь при подписке, но при этом нет способа оповестить того, кто уже подписан.

2024-02-08 14:44 UTC, DimaTrushin commented on Observable.hpp
> +public:
Класс не безопасен.
1) Класс опирается на адрессацию объектов с помощью адреса в памяти. Это должно автоматически сделать объект не перемещаемым. Надо удалить копирующие и перемещающие операторы и конструкторы.
2) Деструктор должен отписывать observable от прослушающего observer-а. Иначе это черевато нарушением инварианта в состоянии ссылок. Observer будет думать что он еще подписан, когда observable уже мертва. И может случайно дернуть ручку у мертвого observable.

2024-02-08 14:44 UTC, DimaTrushin commented on Observable.cpp
> +    observer->SetObservable(this);
Если observer был уже подписан на кого-то, то ты в этом месте ломаешь инвариант другой observable. И у тебя не корректное состояние.

2024-02-08 14:44 UTC, DimaTrushin commented on Observable.cpp
> +template class Observable<ACTrie::SubscribeData, ACTrie::SendData>;
Это плохо. Во-первых, суть этого класса в том, что он библиотечный и как std::vector может быть использован с любыми данными. Во-вторых, если ты внезапно используешь этот класс с другими данными, то они не будут инстанциированы и ошибка будет в линковщике. Потому если уж ты хочешь так делать, то надо static_assert-ом проверять, что шаблонные параметры только те, для которых есть явная инстанциация. Но тут лучше сделать все шаблонным.

2024-02-08 14:44 UTC, DimaTrushin commented on Observer.hpp
> +          on_unsubscribe_(std::move(on_unsubscribe)) {}
Плохо сделано. Дело в том, что тут нужен std::forward. Так как тут не rvalue reference.

2024-02-08 14:44 UTC, DimaTrushin commented on Observer.hpp
> +    on_subscribe_(data);
Ставь assert-ы, что объект не пустой.

2024-02-08 14:44 UTC, DimaTrushin commented on Observer.hpp
> +
Класс не безопасен.
1) Не удалены конструкторы и операторы копирования и перемещения.
2) Нет деструктора в котором делается отписка.

2024-02-08 14:44 UTC, DimaTrushin commented on Observer.hpp
> +    void OnUnsubscribe(UnsubscribeDataType data);
Вранье. У тебя тип данных принимаемых портом является фиксированным инвариантом. Делая такие псевдонимы, ты просто путаешь пользователя класса. Убрать это говно и сделать один тип данных и назвать их просто Data.

Думаю, что стоит сделать эти методы константными.

2024-04-16 15:45 UTC, DimaTrushin requested changes
Сделал пару мелких замечаний.

2024-04-16 15:45 UTC, DimaTrushin commented on App/App.hpp
> +    GraphicsUtils::ImGuiFacade imgui_facade_;
Не используй явные квалификаторы доступа. Заведи в начале класса в приватной части юзинги для таких имен. Ты же для модели завел. Вот и тут сделай.

2024-04-16 15:45 UTC, DimaTrushin commented on App/App.cpp
> +    imgui_facade_.StartRuntimeLoop([this]() { view_.OnNewFrame(); });
Тут достаточно view_ перехватывать. Если перехватываешь this, то я бы ожидал, что ты тут вызываешь приватный метод от App.  И в целом пока выглядит странно, что именно view_ крутится в event loop-е. Но думаю, что на это надо забить.

2024-04-16 15:45 UTC, DimaTrushin commented on App/ACTrieController.hpp
> +namespace AppSpace::Controller {
А зачем создавать пространство имен под контроллер? Это выглядит странно. Пространство имен под один объект. Пространства имен должны делить компоненты по ролям. Я бы сказал, что у тебя есть компоненты ядра и компоненты интерфейса и вот по этим ролям их можно поделить на два пространства имен. Потому что контроллеры бывают разные, они могут связывать два компонента ядра.

2024-04-16 15:45 UTC, DimaTrushin commented on App/App.cpp
> +App::App() : model_controller_(model_) {
Лучше передавать адрес, чтобы было видно, что модель привязывается к контроллеру.

2024-04-16 15:45 UTC, DimaTrushin commented on App/ACTrieController.cpp
> +ACTrieController::ACTrieController(ACTrieModel& host_model)
Лучше тут сразу принимать адрес.

2024-04-16 15:45 UTC, DimaTrushin commented on App/ACTrie.cpp
> +                static_cast<char>(kAlphabetStart + child_node_symbol_index);
Должна быть функция, которая по индексу и алфавиту выдает символ, а не явный каст.

2024-04-16 15:45 UTC, DimaTrushin commented on App/Observer.hpp
> +        assert(listener_ == nullptr);
Выглядит не логично. Ты ниже подписанный обзервер рассматриваешь как штатную ситуацию и отписываешь его. А если у тебя сейчас кто-то подписан, считаешь, что это ошибка программиста.
И еще это получилась по сути mono observable. Но тебе ее хватает конечно.

2024-04-16 15:45 UTC, DimaTrushin commented on App/Observer.hpp
> +        observer->SetObservable(this);
Суть observer паттерна в том, что ты должен оповестить observer-а при подписке, чтобы он был в корректном состоянии с момента подсоединения. Потому я ожидаю тут в конце вызов notify.

2024-04-16 15:45 UTC, DimaTrushin commented on App/Observer.hpp
> +    void Notify(UniTData&& data) {
Ааа, у тебя дизайн такой, что ты явно данные передаешь. Ок, тогда у тебя другой контракт и другие гарантии. В частности это задача программиста не забыть оповестить слушателя при подписке. Это так мысли вслух.

2024-04-16 15:45 UTC, DimaTrushin commented on App/SendTypeHelper.hpp
> +template <class T>
А этот файл у тебя используется более чем в одном хедере?

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/ImGuiFacade.hpp
> +    void StartRuntimeLoop(auto new_frame_code) {
Чтобы избежать шаблонов можно использовать std::function в таких местах. То есть ты просто ставишь стирающий тип в точке, где ты используешь шаблоны. Такое может пригодиться в будущем. Но так тоже можно сделать.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/ImGuiFacade.hpp
> +        void NewFrame() {
Почему код не в cpp файле? Он же не шаблонный.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/GLFWFacade.cpp
> +    : initializer_(),
Не надо звать дефолтный конструктор. Он и так позовется.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/GLFWFacade.hpp
> +    WindowManager window_manager_;
Я так понимаю тут важен порядок полей, чтобы сначало инициализатор сработал и уже потом оконный менеджер. Это стоит прокомментировать, раз класс хрупкий и опирается на порядок инициализации его полей.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/GLFWFacade.hpp
> +        GLFWwindow* window_;
Я не могу понять, это владеющий или нет указатель? Я понял, у тебя менеджер это класс владеющий этим товарищем. То есть это такой holder для окна, а не менеджер окон.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/ImGuiFacade.cpp
> +      context_manager_(),
не надо звать дефолтный конструктор. Или это для того чтобы подчеркнуть порядок конструирования? Если так, то лучше прокомментировать, что код хрупкий и у тебя важен порядок полей в классе.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.hpp
> +    struct Palette final {
Я думаю, что многие из этих вспомогательных классов можно вынести в отдельную h/cpp пару. Например палитру уж точно не стоит тут держать. Просто так ты не будешь засорять класс Drawer лишними деталями, которые иррелевантны для его основной функции.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.hpp
> +    struct EventParams final {
Если эти структуры параметров это данные которые передаются через observable->observer, то хорошо бы их выделить в отдельный файл. Типо идея в том, что классы использующие порты observable observer не будут зависеть друг от друга, они будут зависеть только от портов и передаваемых данных.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.hpp
> +
Очень жирный класс. Он явно делает слишком много. Очень много данных для одного класса. Скорее всего они могут быть сгруппированы по отдельным задачам и сгруппированы в подобъекты.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.hpp
> +    static constexpr std::size_t kPatternInputBufferSize = 64;
Не перемешивай статические и не статические данные. Так сложно понять что на самом деле лежит в объекте.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.cpp
> +    using Ts::operator()...;
Все объявления в cpp файле помести в anonymous namespace.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.cpp
> +void Drawer::HandleNextEvent() {
Мне надо будет подумать как эту проблему решать. Но пусть будет так.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.cpp
> +        const auto speed = static_cast<std::uint32_t>(drawer_show_speed_);
каст

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.cpp
> +    switch (updated_node_info.status) {
Я стараюсь не писать сложную логику в switch блоках (особенно не делать их вложенными). Потому что обычно switch блок это делигирующий блок, который выбирает в зависимости от параметра, какому методу делигировать свои функции.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/Drawer.cpp
Я понимаю, что это сейчас самый проблемный файл. Но все проблемы из-за взаимодействия с незнакомыми внешними библиотеками, которое тяжело сразу облачить в нормальные одежды.

2024-04-16 15:45 UTC, DimaTrushin commented on GraphicsUtils/DrawerUtils/Logger.hpp
> +    void DebugLog(std::string_view msg,
Почему не шаблонные методы не выделены в cpp файл?

2024-04-17 16:47 UTC, i80287 commented on GraphicsUtils/Drawer.hpp
> +    struct EventParams final {
Выбрал плохое название для структуры, переименовал в DrawerEventHandlingDelayParams (константы для расчёта задержки обработки событий, чтобы не сразу доставать их из очереди событий, а с некоторым интервалом)

2024-04-20 12:42 UTC, DimaTrushin approved these changes

2024-04-20 12:43 UTC, DimaTrushin commented
Избавься от static_cast в бизнес логике (спрячь их во вспомогательные функции, которые сразу возвращают данные  в нужном формате).

2024-04-20 20:44 UTC, merged